### PR TITLE
removes newline chars from within tissue location string

### PR DESCRIPTION
**Pull request by allanbolipata**
This should get the sample data clinical to be made properly for helix filters, but let's discuss https://github.com/mskcc/LimsRest/issues/137 before we merge this in.

Waiting on guidance from IGODT.

### CODE REVIEW

**Comment by allanbolipata** [comment]
Let's get this in so we can run some outstanding projects.

This is expected to be overridden by #474

**Comment by nikhil** [comment]
I think this might not work since .replace returns the new string and it does not modify in place

**Comment by nikhil** [comment]
```
>>> sample_str = "remove_me"
>>> sample_str.replace("remove_me","")
''
>>> sample_str
'remove_me'

```

**Comment by nikhil** [comment]
oh nvm, I expanded the the code segment and it looks fine

**Pull request merged**
